### ISSUE TITLE
08/19 version doesn't work

### ISSUE THREAD

**Issue by 1900forever** [Pulkit077/device_xiaomi_rosy#1]
I have tired several times flashing 08/19 version for my Redmi 5. None was working. Then I changed to 07/30 version, flashing was successful. But when I OTA update to 08/19, my phone went black screen after automated update from TWRP.

**Comment by Pulkit077** [comment]
it will be fix in sept update which will come today or tomorrow !
Clean flash was required for 08/19 update, anyways wait for it ((:

**Comment by 1900forever** [comment]
> it will be fix in sept update which will come today or tomorrow !
> Clean flash was required for 08/19 update, anyways wait for it ((:

I did clean flash as well, same problem. And I noticed another issue a few hours ago: the default language is English, but when adding an additional language and switch it to the default language, adding account becomes buggy. The interface swipes with black blocks on the top window.
