### ISSUE TITLE
june-july patch 2021 charging issue

### ISSUE THREAD

**Issue by im-Wanheda** [Pulkit077/device_xiaomi_rosy#2]
I updated my phone to both june and july patch but now the phone is not charging. Earlier when I updated to the june patch the issue was the same but then I downgraded to the may patch. But now may patch is not available on the website can you provude me that.

**Comment by Pulkit077** [comment]
closing this issue as OP confirmed in TG PM later that charging cable was faulty, changing it fixed the issue
